"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestCodes = void 0;
var RequestCodes;
(function (RequestCodes) {
    RequestCodes[RequestCodes["SUCCESS"] = 1] = "SUCCESS";
    RequestCodes[RequestCodes["PARTIAL_DATA"] = 2] = "PARTIAL_DATA";
    RequestCodes[RequestCodes["CONTRACT_ADDRESS_FORMAT"] = 2004] = "CONTRACT_ADDRESS_FORMAT";
    RequestCodes[RequestCodes["INVALID_CHAIN"] = 2018] = "INVALID_CHAIN";
    RequestCodes[RequestCodes["INVALID_CONTRACT"] = 2020] = "INVALID_CONTRACT";
    RequestCodes[RequestCodes["NO_CONTRACT_INFO"] = 2021] = "NO_CONTRACT_INFO";
    RequestCodes[RequestCodes["UNSUPPORTED_CHAIN"] = 2022] = "UNSUPPORTED_CHAIN";
    RequestCodes[RequestCodes["NO_DAPP_INFO"] = 2026] = "NO_DAPP_INFO";
    RequestCodes[RequestCodes["NO_ABI"] = 2027] = "NO_ABI";
    RequestCodes[RequestCodes["UNSUPPORTED_ABI"] = 2028] = "UNSUPPORTED_ABI";
    RequestCodes[RequestCodes["INVALID_APP_KEY"] = 4010] = "INVALID_APP_KEY";
    RequestCodes[RequestCodes["EXPIRED_SIGNATURE"] = 4011] = "EXPIRED_SIGNATURE";
    RequestCodes[RequestCodes["WRONG_SIGNATURE"] = 4012] = "WRONG_SIGNATURE";
    RequestCodes[RequestCodes["ACCESS_TOKEN_NOT_FOUND"] = 4023] = "ACCESS_TOKEN_NOT_FOUND";
    RequestCodes[RequestCodes["REQUEST_LIMIT"] = 4029] = "REQUEST_LIMIT";
    RequestCodes[RequestCodes["SYSTEM_ERROR"] = 5000] = "SYSTEM_ERROR";
    RequestCodes[RequestCodes["PARAM_ERROR"] = 5006] = "PARAM_ERROR";
})(RequestCodes || (exports.RequestCodes = RequestCodes = {}));
